"""
habitat_model_11.py
===================
Phase 3 — Habitat suitability modelling for the MDB Waterbird Pipeline.

Reads from data/processed/ (all files generated by GEE + local pipeline):
  clusters_urban_masked.csv          ← GEE export
  clusters_sentinel2_2016_2017.csv   ← GEE export
  clusters_sentinel2_2018_2019.csv   ← GEE export
  clusters_sentinel2_2020_2021.csv   ← GEE export
  clusters_sentinel2_2022_2023.csv   ← GEE export
  clusters_sentinel2_2024_2025.csv   ← GEE export
  clusters_summary.csv               ← habitat_cluster_09.py output

Workflow:
  1. Merge + recover null columns from clusters_summary.csv
  2. Feature engineering + min-max habitat score normalisation
  3. Random Forest habitat suitability model
  4. Cluster-level suitability ranking
  5. Temporal trend analysis (habitat score 2016–2025)
  6. Publication-quality figures:
       fig_habitat_suitability_map.png
       fig_habitat_score_trends.png
       fig_feature_importance.png
  7. Export: habitat_suitability_final.csv

Usage:
  python habitat_model_11.py
  python habitat_model_11.py --processed path/to/processed/
  python habitat_model_11.py --shapefile path/to/MDB_Basin.gpkg
"""

import os
import sys
import warnings
import argparse
from pathlib import Path

warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from matplotlib.lines import Line2D
import matplotlib.patches as mpatches

from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import cross_val_score, KFold
from sklearn.preprocessing import MinMaxScaler
from sklearn.inspection import permutation_importance
from sklearn.metrics import r2_score

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT      = Path(__file__).resolve().parent
PROCESSED = ROOT / "data" / "processed"
OUTPUTS   = ROOT / "outputs"
OUTPUTS.mkdir(parents=True, exist_ok=True)

DEFAULT_SHAPEFILES = [
    ROOT / "data" / "raw"     / "MDB_Basin.gpkg",
    ROOT / "data" / "spatial" / "mdb_boundary.shp",
    ROOT / "data" / "mdb_boundary.shp",
]

try:
    from src.config_00 import MDB_SHAPEFILE as _CFG_SHP
    DEFAULT_SHAPEFILES.insert(0, _CFG_SHP)
except Exception:
    pass

S2_FILES = [
    "clusters_sentinel2_2016_2017.csv",
    "clusters_sentinel2_2018_2019.csv",
    "clusters_sentinel2_2020_2021.csv",
    "clusters_sentinel2_2022_2023.csv",
    "clusters_sentinel2_2024_2025.csv",
]

MDB_BBOX = {"lat": (-37.6, -23.0), "lon": (138.0, 153.1)}

# ---------------------------------------------------------------------------
# Style — consistent with species_analysis_08 / habitat_cluster_09
# ---------------------------------------------------------------------------
WHITE      = "#FFFFFF"
LIGHT_GREY = "#F4F4F2"
DARK_GREY  = "#2B2B2B"
MID_GREY   = "#7A7A7A"
SPINE_COL  = "#BBBBBB"
LIGHT_LINE = "#E8E8E5"
WATER_COL  = "#EBF3F7"
BASIN_COL  = "#EAF0F5"
BASIN_EDGE = "#6FA8C4"

# Suitability colour ramp — low (white) → high (dark teal)
SUIT_CMAP  = "YlOrRd"

mpl.rcParams.update({
    "figure.facecolor":      LIGHT_GREY,
    "axes.facecolor":        WHITE,
    "axes.edgecolor":        SPINE_COL,
    "axes.linewidth":        0.65,
    "axes.labelcolor":       DARK_GREY,
    "axes.labelsize":        10,
    "axes.titlesize":        11,
    "axes.titlepad":         6,
    "axes.titleweight":      "bold",
    "axes.spines.top":       False,
    "axes.spines.right":     False,
    "axes.grid":             False,
    "xtick.color":           MID_GREY,
    "ytick.color":           MID_GREY,
    "xtick.labelsize":       9,
    "ytick.labelsize":       9,
    "xtick.major.size":      3.0,
    "ytick.major.size":      3.0,
    "xtick.major.width":     0.6,
    "ytick.major.width":     0.6,
    "xtick.direction":       "out",
    "ytick.direction":       "out",
    "text.color":            DARK_GREY,
    "font.family":           "sans-serif",
    "font.sans-serif":       ["Liberation Sans", "Arial", "DejaVu Sans"],
    "font.size":             10,
    "legend.framealpha":     0.96,
    "legend.edgecolor":      SPINE_COL,
    "legend.facecolor":      WHITE,
    "legend.fontsize":       9,
    "legend.borderpad":      0.55,
    "legend.labelspacing":   0.35,
    "savefig.dpi":           300,
    "savefig.bbox":          "tight",
    "savefig.facecolor":     LIGHT_GREY,
    "savefig.pad_inches":    0.06,
})

REGION_COLOURS = {
    "Northern Basin":       "#1F78B4",
    "Southern Basin":       "#33A02C",
    "Lachlan Disconnected": "#FF7F00",
    "Wimmera Disconnected": "#6A3D9A",
    "Coorong, Lower Lakes and Murray Mouth Ramsar site": "#E31A1C",
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def add_panel_label(ax, label, x=-0.10, y=1.05):
    ax.text(x, y, label, transform=ax.transAxes,
            fontsize=12, fontweight="bold", color=DARK_GREY,
            va="top", ha="left")


def style_axis(ax, xlabel="", ylabel="", title="", grid_axis="y"):
    ax.set_xlabel(xlabel, color=DARK_GREY, labelpad=4)
    ax.set_ylabel(ylabel, color=DARK_GREY, labelpad=4)
    if title:
        ax.set_title(title, fontweight="bold", color=DARK_GREY, pad=6)
    ax.grid(visible=True, axis=grid_axis,
            color=LIGHT_LINE, linestyle="-", linewidth=0.5, zorder=0)
    ax.tick_params(axis="both", color=SPINE_COL)
    ax.set_facecolor(WHITE)


def draw_mdb_boundary(ax, shapefile):
    if shapefile and shapefile.exists():
        try:
            import geopandas as gpd
            os.environ.setdefault("PROJ_DATA", "")
            mdb_gdf = gpd.read_file(shapefile)
            bounds  = tuple(mdb_gdf.total_bounds)
            for _, row in mdb_gdf.iterrows():
                polys = list(getattr(row.geometry, "geoms", [row.geometry]))
                for poly in polys:
                    x, y = poly.exterior.xy
                    ax.fill(x, y, color=BASIN_COL, alpha=1.0, zorder=1)
                    ax.plot(x, y, color=SPINE_COL, linewidth=0.25,
                            alpha=0.45, zorder=2)
            for geom in mdb_gdf.geometry:
                polys = list(getattr(geom, "geoms", [geom]))
                for poly in polys:
                    x, y = poly.exterior.xy
                    ax.plot(x, y, color=BASIN_EDGE, linewidth=1.05,
                            zorder=3, alpha=0.90,
                            solid_capstyle="round", solid_joinstyle="round")
            return bounds
        except Exception as e:
            print(f"    Boundary draw skipped ({e}).")
    return (MDB_BBOX["lon"][0], MDB_BBOX["lat"][0],
            MDB_BBOX["lon"][1], MDB_BBOX["lat"][1])


# ---------------------------------------------------------------------------
# Step 1 — Load & merge all data
# ---------------------------------------------------------------------------

def load_and_merge(processed_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Returns:
      panel  — long-format: one row per cluster per year (2620 rows)
      static — one row per cluster (262 rows) with static attributes
    """
    print("  Loading Sentinel-2 annual panels …")
    s2_dfs = []
    for fname in S2_FILES:
        fpath = processed_dir / fname
        if not fpath.exists():
            sys.exit(f"ERROR: {fpath} not found. "
                     f"Place all GEE CSVs in {processed_dir}")
        s2_dfs.append(pd.read_csv(fpath))
    panel = pd.concat(s2_dfs, ignore_index=True)
    print(f"    Combined panel: {panel.shape[0]:,} rows × {panel.shape[1]} cols")

    # Load clusters_summary.csv — authoritative source for static attributes
    summary_paths = [
        processed_dir / "clusters_summary.csv",
        ROOT / "outputs" / "clusters_summary.csv",
    ]
    summary_path = next((p for p in summary_paths if p.exists()), None)
    if summary_path is None:
        sys.exit("ERROR: clusters_summary.csv not found. "
                 "Run habitat_cluster_09.py first.")
    summary = pd.read_csv(summary_path)
    print(f"    Cluster summary: {len(summary)} clusters")

    # Recover columns that GEE dropped (multi_source, has_breeding, etc.)
    recover_cols = ["cluster_id", "multi_source", "has_breeding",
                    "habitat_tier", "total_abundance", "sources", "n_sources"]
    recover_cols = [c for c in recover_cols if c in summary.columns]
    panel = panel.drop(
        columns=[c for c in recover_cols if c != "cluster_id"
                 and c in panel.columns],
        errors="ignore"
    )
    panel = panel.merge(summary[recover_cols], on="cluster_id", how="left")

    # Static view — mean across all years per cluster
    static_cols = ["cluster_id", "region", "centroid_lat", "centroid_lon",
                   "multi_source", "has_breeding", "habitat_tier",
                   "total_abundance", "n_points", "n_species", "n_years",
                   "extent_km", "urban_fraction_pct", "n_sources", "sources"]
    static_cols = [c for c in static_cols if c in panel.columns]
    static = panel[static_cols].drop_duplicates(subset=["cluster_id"])

    print(f"    Null check — multi_source: {panel['multi_source'].isna().sum()}, "
          f"has_breeding: {panel['has_breeding'].isna().sum()}")
    return panel, static


# ---------------------------------------------------------------------------
# Step 2 — Feature engineering + habitat score normalisation
# ---------------------------------------------------------------------------

def engineer_features(panel: pd.DataFrame) -> pd.DataFrame:
    print("  Engineering features …")

    # Recalculate raw score (NDWI dominant — wetland signal)
    panel["habitat_score_raw"] = panel["NDWI"] * 0.6 + panel["NDVI"] * 0.4

    # Min-max normalise per year so scores are comparable across years
    panel["habitat_score"] = panel.groupby("year")["habitat_score_raw"] \
        .transform(lambda x: (x - x.min()) / (x.max() - x.min() + 1e-9))

    # Wetland index: positive NDWI = surface water / wetland
    panel["is_wetland"] = (panel["NDWI"] > 0).astype(int)

    # Vegetation vigour: NDVI z-score within year
    panel["ndvi_zscore"] = panel.groupby("year")["NDVI"] \
        .transform(lambda x: (x - x.mean()) / (x.std() + 1e-9))

    # Interannual stability: std of habitat_score across years per cluster
    stability = panel.groupby("cluster_id")["habitat_score"] \
        .std().reset_index().rename(columns={"habitat_score": "score_stability"})
    panel = panel.merge(stability, on="cluster_id", how="left")

    print(f"    habitat_score range: "
          f"{panel['habitat_score'].min():.3f} – {panel['habitat_score'].max():.3f}")
    print(f"    Wetland clusters (NDWI>0): "
          f"{panel[panel['is_wetland']==1]['cluster_id'].nunique()} "
          f"unique clusters")
    return panel


# ---------------------------------------------------------------------------
# Step 3 — Random Forest suitability model
# ---------------------------------------------------------------------------

FEATURES = ["NDVI", "NDWI", "EVI",
            "extent_km", "ndvi_zscore", "score_stability"]

def train_model(panel: pd.DataFrame) -> tuple:
    print("  Training Random Forest habitat suitability model …")

    # Use mean across years per cluster for a stable static model
    cluster_mean = panel.groupby("cluster_id")[FEATURES + ["total_abundance"]] \
        .mean().reset_index()
    cluster_mean = cluster_mean.dropna(subset=FEATURES + ["total_abundance"])

    X = cluster_mean[FEATURES].to_numpy(dtype=float)
    y = np.log1p(
        (cluster_mean["total_abundance"] / cluster_mean["extent_km"].clip(lower=0.1))
        .to_numpy(dtype=float)
    )
    rf = RandomForestRegressor(
        n_estimators=300,
        max_depth=8,
        min_samples_leaf=3,
        random_state=42,
        n_jobs=-1
    )
    rf.fit(X, y)

    # Cross-validated R²
    cv   = KFold(n_splits=5, shuffle=True, random_state=42)
    cvr2 = cross_val_score(rf, X, y, cv=cv, scoring="r2")
    print(f"    CV R² = {cvr2.mean():.3f} ± {cvr2.std():.3f}")

    # Predict suitability for all clusters (mean features)
    raw_pred = rf.predict(X)
    pmin, pmax = raw_pred.min(), raw_pred.max()
    cluster_mean["predicted_suitability"] = (raw_pred - pmin) / (pmax - pmin + 1e-9)

    # Permutation importance for interpretability
    perm_result = permutation_importance(rf, X, y, n_repeats=20, random_state=42)
    importance_df = pd.DataFrame({
        "feature":    FEATURES,
        "importance": np.array(perm_result["importances_mean"]),
        "std":        np.array(perm_result["importances_std"]),
    }).sort_values("importance", ascending=False)

    print(f"\n    Feature importances:")
    for _, row in importance_df.iterrows():
        print(f"      {row['feature']:20s}  {row['importance']:.4f} ± {row['std']:.4f}")

    return rf, cluster_mean, importance_df, cvr2


# ---------------------------------------------------------------------------
# Step 4 — Merge predictions back to static + panel
# ---------------------------------------------------------------------------

def build_final(panel: pd.DataFrame, static: pd.DataFrame,
                cluster_mean: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:

    pred_cols = ["cluster_id", "predicted_suitability"]
    static = static.merge(cluster_mean[pred_cols], on="cluster_id", how="left")

    # Suitability tier
    q33 = static["predicted_suitability"].quantile(0.33)
    q66 = static["predicted_suitability"].quantile(0.66)
    static["suitability_tier"] = pd.cut(
        static["predicted_suitability"],
        bins=[-np.inf, q33, q66, np.inf],
        labels=["Low", "Moderate", "High"]
    )

    # Annual trends — mean habitat_score per year × region
    trend = panel.groupby(["year", "region"])["habitat_score"] \
        .agg(["mean", "std"]).reset_index()
    trend.columns = ["year", "region", "mean_score", "std_score"]

    print(f"\n  High suitability clusters : "
          f"{(static['suitability_tier']=='High').sum()}")
    print(f"  Moderate suitability      : "
          f"{(static['suitability_tier']=='Moderate').sum()}")
    print(f"  Low suitability           : "
          f"{(static['suitability_tier']=='Low').sum()}")

    return static, trend


# ---------------------------------------------------------------------------
# Figure A — Habitat suitability map
# ---------------------------------------------------------------------------

def fig_suitability_map(static: pd.DataFrame, shapefile):
    print("  Generating fig_habitat_suitability_map.png …")

    fig, (ax_map, ax_rank) = plt.subplots(
        1, 2, figsize=(18, 9), facecolor=LIGHT_GREY,
        gridspec_kw={"wspace": 0.25, "width_ratios": [2, 1]}
    )

    # --- Map ---
    ax_map.set_facecolor(WATER_COL)
    bounds = draw_mdb_boundary(ax_map, shapefile)
    pad = 0.35
    ax_map.set_xlim(bounds[0] - pad, bounds[2] + pad)
    ax_map.set_ylim(bounds[1] - pad, bounds[3] + pad)

    sc = ax_map.scatter(
        static["centroid_lon"], static["centroid_lat"],
        c=static["predicted_suitability"],
        cmap=SUIT_CMAP, vmin=0, vmax=1,
        s=static["extent_km"].clip(2, 100) * 1.5 + 8,
        alpha=0.85, zorder=4,
        edgecolors="white", linewidths=0.3, rasterized=True
    )

    # Star breeding confirmed sites
    breed = static[static["has_breeding"] == True]
    ax_map.scatter(breed["centroid_lon"], breed["centroid_lat"],
                   s=80, marker="*", color="#FFFFFF", zorder=6,
                   edgecolors=DARK_GREY, linewidths=0.5,
                   label=f"Breeding confirmed ({len(breed)})")

    cbar = fig.colorbar(sc, ax=ax_map, fraction=0.025, pad=0.02)
    cbar.set_label("Predicted habitat suitability (0–1)",
                   fontsize=9, color=DARK_GREY)
    cbar.ax.tick_params(labelsize=8)

    ax_map.set_aspect("equal")
    ax_map.set_xlabel("Longitude (°E)", fontsize=9, color=DARK_GREY, labelpad=4)
    ax_map.set_ylabel("Latitude (°N)",  fontsize=9, color=DARK_GREY, labelpad=4)
    ax_map.tick_params(labelsize=8.5, color=SPINE_COL, direction="out")
    ax_map.grid(visible=True, color="#D4E7F0", linestyle="-",
                linewidth=0.28, alpha=0.55, zorder=0)
    for sp in ax_map.spines.values():
        sp.set_visible(True)
        sp.set_edgecolor(SPINE_COL)
        sp.set_linewidth(0.65)

    ax_map.set_title(
        "Predicted waterbird habitat suitability  ·  Murray–Darling Basin\n"
        "Dot size ∝ cluster extent (km).  ★ = breeding confirmed.",
        fontweight="bold", color=DARK_GREY, pad=7
    )
    leg = ax_map.legend(loc="upper left", fontsize=8.5,
                        framealpha=0.96, edgecolor=SPINE_COL)
    leg.get_frame().set_linewidth(0.5)
    add_panel_label(ax_map, "a", x=-0.04)

    # --- Ranked bar chart by region ---
    top30 = static.nlargest(30, "predicted_suitability").reset_index(drop=True)
    colors_bar = [REGION_COLOURS.get(r, MID_GREY) for r in top30["region"]]

    ax_rank.barh(range(len(top30)), top30["predicted_suitability"],
                 color=colors_bar, alpha=0.85, zorder=3, height=0.7,
                 edgecolor="white", linewidth=0.3)
    ax_rank.set_yticks(range(len(top30)))
    ax_rank.set_yticklabels(
        [f"Cluster {int(r)}" for r in top30["cluster_id"]], fontsize=7.5)
    ax_rank.invert_yaxis()
    ax_rank.set_xlim(0, 1.05)
    style_axis(ax_rank, xlabel="Predicted suitability",
               title="Top-30 habitat clusters", grid_axis="x")
    ax_rank.spines["left"].set_visible(False)
    ax_rank.tick_params(left=False)

    # region legend
    handles = [mpatches.Patch(color=c, label=r)
               for r, c in REGION_COLOURS.items()]
    leg2 = ax_rank.legend(handles=handles, loc="lower right",
                          fontsize=7, framealpha=0.96, edgecolor=SPINE_COL)
    leg2.get_frame().set_linewidth(0.5)
    add_panel_label(ax_rank, "b")

    out = OUTPUTS / "fig_habitat_suitability_map.png"
    fig.savefig(out, facecolor=LIGHT_GREY)
    plt.close(fig)
    print(f"    Saved → {out}")


# ---------------------------------------------------------------------------
# Figure B — Temporal habitat score trends (2016–2025) by region
# ---------------------------------------------------------------------------

def fig_score_trends(trend: pd.DataFrame, panel: pd.DataFrame):
    print("  Generating fig_habitat_score_trends.png …")

    regions = [r for r in REGION_COLOURS if r in trend["region"].unique()]
    years   = sorted(trend["year"].unique().astype(int))

    fig, (ax_line, ax_box) = plt.subplots(
        1, 2, figsize=(18, 8), facecolor=LIGHT_GREY,
        gridspec_kw={"wspace": 0.30}
    )

    # --- Line: mean score per region per year ---
    for region in regions:
        sub   = trend[trend["region"] == region].sort_values("year")
        color = REGION_COLOURS[region]
        label = region if len(region) < 30 else region[:28] + "…"
        ax_line.plot(sub["year"], sub["mean_score"],
                     color=color, linewidth=2, marker="o",
                     markersize=4, zorder=3, label=label)
        ax_line.fill_between(
            sub["year"],
            sub["mean_score"] - sub["std_score"],
            sub["mean_score"] + sub["std_score"],
            color=color, alpha=0.10, zorder=2
        )

    style_axis(ax_line,
               xlabel="Year",
               ylabel="Mean habitat score (normalised 0–1)",
               title="Habitat suitability score trends by sub-basin  ·  2016–2025")
    ax_line.set_xticks(years)
    ax_line.set_xticklabels(years, rotation=35, ha="right")
    ax_line.set_ylim(0, 1)
    ax_line.legend(loc="upper left", fontsize=8, framealpha=0.96,
                   edgecolor=SPINE_COL)
    add_panel_label(ax_line, "a")

    # --- Box: score distribution per year (all clusters) ---
    year_data = [panel[panel["year"] == yr]["habitat_score"].dropna().values
                 for yr in years]
    bp = ax_box.boxplot(year_data, positions=years, widths=0.55,
                        patch_artist=True, notch=False,
                        medianprops=dict(color=DARK_GREY, linewidth=1.5),
                        whiskerprops=dict(color=MID_GREY, linewidth=0.8),
                        capprops=dict(color=MID_GREY, linewidth=0.8),
                        flierprops=dict(marker=".", color=MID_GREY,
                                        alpha=0.3, markersize=3))
    for patch in bp["boxes"]:
        patch.set_facecolor("#1F78B4")
        patch.set_alpha(0.35)
        patch.set_edgecolor(SPINE_COL)

    style_axis(ax_box,
               xlabel="Year",
               ylabel="Habitat score distribution (all clusters)",
               title="Annual habitat score distribution  ·  all MDB clusters")
    ax_box.set_xticks(years)
    ax_box.set_xticklabels(years, rotation=35, ha="right")
    ax_box.set_ylim(0, 1)
    add_panel_label(ax_box, "b")

    out = OUTPUTS / "fig_habitat_score_trends.png"
    fig.savefig(out, facecolor=LIGHT_GREY)
    plt.close(fig)
    print(f"    Saved → {out}")


# ---------------------------------------------------------------------------
# Figure C — Feature importance
# ---------------------------------------------------------------------------

def fig_feature_importance(importance_df: pd.DataFrame, cvr2: np.ndarray):
    print("  Generating fig_feature_importance.png …")

    FEATURE_LABELS = {
        "NDVI":            "NDVI  (vegetation greenness)",
        "NDWI":            "NDWI  (water/wetland surface)",
        "EVI":             "EVI  (enhanced vegetation)",
        "n_points":        "Survey density (n points)",
        "n_species":       "Species richness",
        "n_years":         "Survey years (n)",
        "extent_km":       "Cluster extent (km)",
        "ndvi_zscore":     "NDVI z-score (relative greenness)",
        "score_stability": "Score stability (inter-annual)",
    }

    importance_df = importance_df.copy()
    importance_df["label"] = importance_df["feature"].map(FEATURE_LABELS)
    importance_df = importance_df.sort_values("importance", ascending=True)

    fig, ax = plt.subplots(figsize=(12, 7), facecolor=LIGHT_GREY)
    ax.set_facecolor(DARK_GREY)
    colors = ["#E31A1C" if imp > importance_df["importance"].median()
              else "#1F78B4"
              for imp in importance_df["importance"]]

    bars = ax.barh(range(len(importance_df)), importance_df["importance"],
                   xerr=importance_df["std"],
                   color=colors, alpha=0.82, zorder=3, height=0.6,
                   edgecolor="white", linewidth=0.3,
                   error_kw=dict(ecolor=MID_GREY, capsize=3,
                                 elinewidth=0.8, capthick=0.8))

    ax.set_yticks(range(len(importance_df)))
    ax.set_yticklabels(importance_df["label"], fontsize=9.5)
    ax.spines["left"].set_visible(False)
    ax.tick_params(left=False)

    style_axis(ax,
               xlabel="Permutation importance (mean decrease in R²)",
               title=(f"Random Forest feature importances  ·  "
                      f"CV R² = {cvr2.mean():.3f} ± {cvr2.std():.3f}  "
                      f"(5-fold)"),
               grid_axis="x")

    # Legend
    handles = [
        mpatches.Patch(color="#E31A1C", alpha=0.82,
                       label="Above-median importance"),
        mpatches.Patch(color="#1F78B4", alpha=0.82,
                       label="Below-median importance"),
    ]
    ax.legend(handles=handles, loc="lower right", fontsize=9,
              framealpha=0.96, edgecolor=SPINE_COL)
    add_panel_label(ax, "a")

    out = OUTPUTS / "fig_feature_importance.png"
    fig.savefig(out, facecolor=LIGHT_GREY)
    plt.close(fig)
    print(f"    Saved → {out}")


# ---------------------------------------------------------------------------
# Export final CSV
# ---------------------------------------------------------------------------

def export_final(static: pd.DataFrame, panel: pd.DataFrame):
    # Static: one row per cluster with predicted suitability
    out_static = OUTPUTS / "habitat_suitability_final.csv"
    static.to_csv(out_static, index=False)
    print(f"    Saved → {out_static}")

    # Annual: full panel with habitat scores — for habitat_model use
    out_panel = OUTPUTS / "habitat_scores_annual.csv"
    panel.to_csv(out_panel, index=False)
    print(f"    Saved → {out_panel}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="MDB habitat suitability model — Phase 3")
    parser.add_argument("--processed",  type=str, default=None,
                        help="Path to processed/ folder with GEE CSVs")
    parser.add_argument("--shapefile",  type=str, default=None)
    args = parser.parse_args()

    processed_dir = (Path(args.processed) if args.processed else PROCESSED)
    shapefile = (Path(args.shapefile) if args.shapefile
                 else next((p for p in DEFAULT_SHAPEFILES if p.exists()), None))

    if shapefile and shapefile.exists():
        print(f"  Shapefile: {shapefile}")
    else:
        print("  Shapefile not found — bbox fallback.")
        shapefile = None

    print("\n" + "=" * 60)
    print("  MDB WATERBIRD PIPELINE — habitat_model_11.py")
    print("=" * 60)

    # Steps
    panel, static    = load_and_merge(processed_dir)
    panel            = engineer_features(panel)
    rf, cluster_mean, importance_df, cvr2 = train_model(panel)
    static, trend    = build_final(panel, static, cluster_mean)

    print("\n  Generating figures …")
    fig_suitability_map(static, shapefile)
    fig_score_trends(trend, panel)
    fig_feature_importance(importance_df, cvr2)

    print("\n  Exporting CSVs …")
    export_final(static, panel)

    print("\n" + "=" * 60)
    print("  Outputs written to: outputs/")
    print("  fig_habitat_suitability_map.png")
    print("  fig_habitat_score_trends.png")
    print("  fig_feature_importance.png")
    print("  habitat_suitability_final.csv")
    print("  habitat_scores_annual.csv")
    print("=" * 60 + "\n")


if __name__ == "__main__":
    main()